name: Release Distributions
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
concurrency:
  group: release-distributions
  cancel-in-progress: true
jobs:
  build-ios:
    if: github.event.pull_request.merged == true
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set build flavor to release
        run: printf "\n%s" "buildkonfig.flavor=release" >> gradle.properties
      - uses: ./.github/actions/setup-build-env
      - name: Build with xcodebuild
        working-directory: iosApp/
        run: xcodebuild archive PRODUCT_NAME=HachimiWorld CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - uses: ./.github/actions/get-version-info
      - name: Package IPA
        working-directory: iosApp/build
        run: |
          FILE_NAME="hachimi-world-${VERSION_NAME}-${VERSION_CODE}-unsigned.ipa"
          echo "FILE_NAME=$FILE_NAME" >> "$GITHUB_ENV"
          mkdir -p Payload
          cp -r Release-iphoneos/HachimiWorld.app/ Payload/HachimiWorld.app
          mkdir -p ipa
          zip -r "ipa/${FILE_NAME}" Payload
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: iosApp/build/ipa
          file_pattern: '*.ipa'
          file_extension: '.ipa'
          file_suffix: '-unsigned'
          s3_destination: distribution/ios/
          variant: release-ios
          artifact_name: ios

  build-macos:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build rust library
        working-directory: ./rustLib
        run: |
          cargo build -r --lib
          cp target/release/libhachimi.dylib ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/libhachimi.dylib \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
      - name: Build with Gradle
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/dmg
          file_pattern: '*.dmg'
          file_extension: '.dmg'
          s3_destination: distribution/macos/
          variant: release-macos
          artifact_name: macos

  build-windows:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build rust library
        working-directory: ./rustLib
        shell: bash
        run: |
          cargo build -r --lib
          cp target/release/hachimi.dll ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/hachimi.dll \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
      - name: Build with Gradle
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/msi
          file_pattern: '*.msi'
          file_extension: '.msi'
          s3_destination: distribution/windows/
          variant: release-windows
          artifact_name: windows

  build-linux:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt install libasound2-dev
          sudo apt install libdbus-1-dev
      - name: Build rust library
        working-directory: ./rustLib
        run: |
          cargo build -r --lib
          cp target/release/libhachimi.so ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/libhachimi.so \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
      - name: Build with Gradle
        run: ./gradlew desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/deb
          file_pattern: '*.deb'
          file_extension: '.deb'
          s3_destination: distribution/linux/
          variant: release-linux
          artifact_name: linux

  build-android:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > androidApp/android.jks
      - uses: ./.github/actions/setup-build-env
      - name: Build Release APK
        run: ./gradlew :androidApp:assembleRelease -P buildkonfig.flavor=release
        env:
          IS_CI: true
          ANDROID_KEYSTORE_FILE: android.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: build/reports/problems
      - uses: ./.github/actions/get-version-info
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: androidApp/build/outputs/apk/release
          file_pattern: '*.apk'
          file_extension: '.apk'
          s3_destination: distribution/android/
          variant: release-android
          artifact_name: android

