name: Test Release Distributions
on:
  pull_request:
    types: [ closed ]
    branches: [ test/release-distribution ]
concurrency:
  group: test-release-distributions
  cancel-in-progress: true
jobs:
  build-ios:
    if: github.event.pull_request.merged == true
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute short hash
        run: echo "SHORT_HASH=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Set build flavor to release
        run: printf "\n%s" "buildkonfig.flavor=release" >> gradle.properties
      - uses: ./.github/actions/setup-build-env
        with:
          config_api_base_url: ${{ secrets.CONFIG_API_BASE_URL }}
          config_assets_base_url: ${{ secrets.CONFIG_ASSETS_BASE_URL }}
      - name: Build with xcodebuild
        working-directory: iosApp/
        run: xcodebuild archive PRODUCT_NAME=HachimiWorld CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - uses: ./.github/actions/get-version-info
        id: versions
      - name: Set version env
        run: |
          echo "VERSION_NAME=${{ steps.versions.outputs.VERSION_NAME }}" >> "$GITHUB_ENV"
          echo "VERSION_CODE=${{ steps.versions.outputs.VERSION_CODE }}" >> "$GITHUB_ENV"

      - name: Package IPA
        working-directory: iosApp/build
        run: |
          FILE_NAME="hachimi-world-${VERSION_NAME}-${VERSION_CODE}-unsigned.ipa"
          echo "FILE_NAME=$FILE_NAME" >> "$GITHUB_ENV"
          mkdir -p Payload
          cp -r Release-iphoneos/HachimiWorld.app/ Payload/HachimiWorld.app
          mkdir -p ipa
          zip -r "ipa/${FILE_NAME}" Payload
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: iosApp/build/ipa
          file_pattern: '*.ipa'
          file_extension: '.ipa'
          file_suffix: '-unsigned'
          s3_destination: distribution_${{ env.SHORT_HASH }}/ios/
          variant: ${{ env.SHORT_HASH }}-ios
          artifact_name: ios
          version_name: ${{ steps.versions.outputs.VERSION_NAME }}
          version_code: ${{ steps.versions.outputs.VERSION_CODE }}
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_domain: ${{ secrets.S3_DOMAIN }}
          publish_version_token: ${{ secrets.PUBLISH_VERSION_TOKEN }}
          publish_version_url: ${{ secrets.PUBLISH_VERSION_URL }}

  build-macos:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute short hash
        run: echo "SHORT_HASH=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build rust library
        working-directory: ./rustLib
        run: |
          cargo build -r --lib
          cp target/release/libhachimi.dylib ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/libhachimi.dylib \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
        with:
          config_api_base_url: ${{ secrets.CONFIG_API_BASE_URL }}
          config_assets_base_url: ${{ secrets.CONFIG_ASSETS_BASE_URL }}
      - name: Build with Gradle
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
        id: versions
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/dmg
          file_pattern: '*.dmg'
          file_extension: '.dmg'
          s3_destination: distribution_${{ env.SHORT_HASH }}/macos/
          variant: ${{ env.SHORT_HASH }}-macos
          artifact_name: macos
          version_name: ${{ steps.versions.outputs.VERSION_NAME }}
          version_code: ${{ steps.versions.outputs.VERSION_CODE }}
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_domain: ${{ secrets.S3_DOMAIN }}
          publish_version_token: ${{ secrets.PUBLISH_VERSION_TOKEN }}
          publish_version_url: ${{ secrets.PUBLISH_VERSION_URL }}

  build-windows:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute short hash
        run: echo "SHORT_HASH=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build rust library
        working-directory: ./rustLib
        shell: bash
        run: |
          cargo build -r --lib
          cp target/release/hachimi.dll ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/hachimi.dll \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
        with:
          config_api_base_url: ${{ secrets.CONFIG_API_BASE_URL }}
          config_assets_base_url: ${{ secrets.CONFIG_ASSETS_BASE_URL }}
      - name: Build with Gradle
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
        id: versions
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/msi
          file_pattern: '*.msi'
          file_extension: '.msi'
          s3_destination: distribution_${{ env.SHORT_HASH }}/windows/
          variant: ${{ env.SHORT_HASH }}-windows
          artifact_name: windows
          version_name: ${{ steps.versions.outputs.VERSION_NAME }}
          version_code: ${{ steps.versions.outputs.VERSION_CODE }}
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_domain: ${{ secrets.S3_DOMAIN }}
          publish_version_token: ${{ secrets.PUBLISH_VERSION_TOKEN }}
          publish_version_url: ${{ secrets.PUBLISH_VERSION_URL }}

  build-linux:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute short hash
        run: echo "SHORT_HASH=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rustLib/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt install libasound2-dev
          sudo apt install libdbus-1-dev
      - name: Build rust library
        working-directory: ./rustLib
        run: |
          cargo build -r --lib
          cp target/release/libhachimi.so ../composeApp/src/jvmMain/resources
          cargo run --bin uniffi-bindgen generate \
            --library target/release/libhachimi.so \
            --language kotlin --out-dir ../composeApp/src/jvmMain/kotlin
      - uses: ./.github/actions/setup-build-env
        with:
          config_api_base_url: ${{ secrets.CONFIG_API_BASE_URL }}
          config_assets_base_url: ${{ secrets.CONFIG_ASSETS_BASE_URL }}
      - name: Build with Gradle
        run: ./gradlew desktopApp:packageDistributionForCurrentOS -P buildkonfig.flavor=release
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: desktopApp/build/compose/logs/
      - uses: ./.github/actions/get-version-info
        id: versions
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: desktopApp/build/compose/binaries/main/deb
          file_pattern: '*.deb'
          file_extension: '.deb'
          s3_destination: distribution_${{ env.SHORT_HASH }}/linux/
          variant: ${{ env.SHORT_HASH }}-linux
          artifact_name: linux
          version_name: ${{ steps.versions.outputs.VERSION_NAME }}
          version_code: ${{ steps.versions.outputs.VERSION_CODE }}
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_domain: ${{ secrets.S3_DOMAIN }}
          publish_version_token: ${{ secrets.PUBLISH_VERSION_TOKEN }}
          publish_version_url: ${{ secrets.PUBLISH_VERSION_URL }}

  build-android:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute short hash
        run: echo "SHORT_HASH=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> "$GITHUB_ENV"
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > androidApp/android.jks
      - uses: ./.github/actions/setup-build-env
        with:
          config_api_base_url: ${{ secrets.CONFIG_API_BASE_URL }}
          config_assets_base_url: ${{ secrets.CONFIG_ASSETS_BASE_URL }}
      - name: Build Release APK
        run: ./gradlew :androidApp:assembleRelease -P buildkonfig.flavor=release
        env:
          IS_CI: true
          ANDROID_KEYSTORE_FILE: android.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-logs
          path: build/reports/problems
      - uses: ./.github/actions/get-version-info
        id: versions
      - uses: ./.github/actions/publish-artifact
        with:
          source_dir: androidApp/build/outputs/apk/release
          file_pattern: '*.apk'
          file_extension: '.apk'
          s3_destination: distribution_${{ env.SHORT_HASH }}/android/
          variant: ${{ env.SHORT_HASH }}-android
          artifact_name: android
          version_name: ${{ steps.versions.outputs.VERSION_NAME }}
          version_code: ${{ steps.versions.outputs.VERSION_CODE }}
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_key_id: ${{ secrets.S3_KEY_ID }}
          s3_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          s3_domain: ${{ secrets.S3_DOMAIN }}
          publish_version_token: ${{ secrets.PUBLISH_VERSION_TOKEN }}
          publish_version_url: ${{ secrets.PUBLISH_VERSION_URL }}
